version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - mynet

  bot:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MUTE_DURATION=${MUTE_DURATION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - mynet


networks:
  mynet:
    driver: bridge